using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

namespace PaperFlow;

// 下拉框里的一项：Value 是存进配置的规范值，Label 是当前语言下显示的文字。
// 用 record 而不是两个平行数组，避免以后改一处忘另一处。
// 自定义的下拉框模板不认 DisplayMemberPath（它直接显示整个对象），
// 所以让 ToString 就返回显示文字：选中框和下拉列表都会拿到正确的字。
public sealed record Choice(string Value, string Label)
{
    public override string ToString() => Label;
}

// 界面语言。数据里存的永远是中文规范值——阶段名、优先级、状态、主题名、排序方式、
// 事件历史都是中文，切语言只换显示。所以老版本、老同步记录、两台语言不同的电脑
// 之间都不会因为语言产生任何差异，也不需要迁移数据。
public static class Lang
{
    public const string Auto = "auto", Chinese = "zh", English = "en";
    public static string Current { get; private set; } = Chinese;
    public static bool IsEnglish => Current == English;

    // "auto" 看 Windows 的显示语言；其它值只认 zh / en，别的都当 auto。
    public static string Normalize(string? stored) => stored is Chinese or English ? stored : Auto;
    // 真正生效的语言：auto 再去看 Windows 的显示语言。比较“语言有没有变”时要比这个值。
    public static string Effective(string? stored) => Normalize(stored) is string wanted && wanted != Auto
        ? wanted
        : CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "zh" ? Chinese : English;
    public static void Apply(string? stored) => Current = Effective(stored);

    // 语言选择本身：中文在英文界面里也写“中文”，英文永远写“English”，只有“跟随系统”跟着翻。
    public static IReadOnlyList<Choice> LanguageChoices() => new List<Choice>
    {
        new(Auto, T("跟随系统")), new(Chinese, "中文"), new(English, "English")
    };

    public static string T(string chinese) => !IsEnglish ? chinese : Table.TryGetValue(chinese, out var english) ? english : chinese;
    // 列表分隔符：中文用顿号，英文用逗号。
    public static string ListSeparator => IsEnglish ? ", " : "、";
    public static string F(string chinese, params object?[] arguments) => string.Format(T(chinese), arguments);
    // 英文里 1 day / 3 days 要换形；中文只用一个模板。
    public static string P(int count, string chinese, string englishOne, string englishMany, params object?[] arguments)
        => string.Format(IsEnglish ? (count == 1 ? englishOne : englishMany) : chinese, arguments);

    // 数据值照原样显示（阶段、优先级、状态、主题名、排序方式……）。
    public static string Value(string stored) => T(stored);
    public static string Stage(int index) => T(Paper.StageLabels[Math.Clamp(index, 0, Paper.StageLabels.Length - 1)]);
    public static IReadOnlyList<Choice> Choices(IEnumerable<string> values) => values.Select(v => new Choice(v, T(v))).ToList();

    // 修改记录是存进资料、会同步的老文字，所以只在显示时翻译：
    // 整句能对上就整句换，对不上就按“ · ”拆开，逐段换（例如“完成 · 在审”）。
    public static string History(string stored)
    {
        if (!IsEnglish || stored.Length == 0) return stored;
        if (Table.TryGetValue(stored, out var whole)) return whole;
        if (stored.StartsWith("优先级设为", StringComparison.Ordinal)) return "Priority set to " + T(stored["优先级设为".Length..]);
        return stored.Contains(" · ") ? string.Join(" · ", stored.Split(" · ").Select(T)) : stored;
    }

    public static bool Has(string chinese) => Table.ContainsKey(chinese);
    // 给测试用：整张词表。运行时不改它。
    public static IReadOnlyDictionary<string, string> Entries => Table;

    private static readonly Dictionary<string, string> Table = new(StringComparer.Ordinal)
    {
        // ---------- 数据值：阶段、优先级、状态 ----------
        ["开题"] = "Proposal",
        ["语料&数据整理"] = "Corpus & data",
        ["初稿"] = "First draft",
        ["自修"] = "Self-revision",
        ["投稿"] = "Submission",
        ["在审"] = "Under review",
        ["返修"] = "Revision",
        ["收录"] = "Accepted",
        ["高"] = "High",
        ["中"] = "Medium",
        ["低"] = "Low",
        ["准备中"] = "Preparing",
        ["写作中"] = "Writing",
        ["审稿中"] = "In review",
        ["待返修"] = "Revision needed",
        ["已修回"] = "Revision sent",
        ["已录用"] = "Accepted",
        ["准备转投"] = "Resubmitting",
        ["暂停"] = "Paused",
        ["阶段已全部完成"] = "All stages complete",
        ["今天截止"] = "Due today",
        ["明天截止"] = "Due tomorrow",
        ["已逾期 {0} 天"] = "Overdue by {0} days",
        ["还剩 {0} 天"] = "{0} days left",
        ["导入文件超过 30 MB。"] = "The import file is larger than 30 MB.",
        // ---------- 数据值：翻页、排序、音效 ----------
        ["不翻页"] = "One page",
        ["按优先级翻页"] = "Page by priority",
        ["按阶段分组翻页"] = "Page by stage",
        ["手动排序"] = "Manual order",
        ["最近修改"] = "Recently edited",
        ["截止日期"] = "Due date",
        ["进度优先"] = "Progress first",
        ["关"] = "Off",
        ["只完成时"] = "On completion",
        ["完成和取消都响"] = "Completion and undo",
        ["木质"] = "Wood",
        ["清脆"] = "Crisp",
        ["水滴"] = "Water drop",
        // ---------- 数据值：布局、风格、主题 ----------
        ["卡片"] = "Cards",
        ["列表"] = "List",
        ["纸感"] = "Paper",
        ["柔光"] = "Soft light",
        ["夜航"] = "Night flight",
        ["标签"] = "Tags",
        ["极简"] = "Minimal",
        ["经典"] = "Classic",
        ["纸感 · 竹青"] = "Paper · Bamboo",
        ["纸感 · 雾蓝"] = "Paper · Mist blue",
        ["纸感 · 石墨"] = "Paper · Graphite",
        ["纸感 · 松绿"] = "Paper · Pine",
        ["柔光 · 陶土"] = "Soft light · Terracotta",
        ["柔光 · 米杏"] = "Soft light · Apricot",
        ["柔光 · 橄榄"] = "Soft light · Olive",
        ["柔光 · 藕荷"] = "Soft light · Lotus",
        ["夜航 · 霜蓝"] = "Night flight · Frost blue",
        ["夜航 · 苔绿"] = "Night flight · Moss",
        ["夜航 · 琥珀"] = "Night flight · Amber",
        ["夜航 · 靛紫"] = "Night flight · Indigo",
        ["标签 · 蓝"] = "Tags · Blue",
        ["标签 · 紫"] = "Tags · Violet",
        ["标签 · 橙"] = "Tags · Orange",
        ["极简 · 白"] = "Minimal · Light",
        ["极简 · 夜"] = "Minimal · Night",
        ["经典 · 竹青"] = "Classic · Bamboo",
        ["经典 · 纸白"] = "Classic · Paper white",
        ["经典 · 雾蓝"] = "Classic · Mist blue",
        ["经典 · 暖杏"] = "Classic · Warm apricot",
        ["经典 · 夜墨"] = "Classic · Ink",
        ["经典 · 透明"] = "Classic · Transparent",
        ["竹青"] = "Bamboo",
        ["纸白"] = "Paper white",
        ["雾蓝"] = "Mist blue",
        ["暖杏"] = "Warm apricot",
        ["夜墨"] = "Ink",
        ["透明"] = "Transparent",
        ["深色"] = "Dark",
        ["跟随主题"] = "Follow theme",
        ["跟随系统"] = "Follow system",
        // ---------- 修改记录（存进去的老文字，显示时翻译） ----------
        ["完成"] = "Completed",
        ["撤销完成"] = "Undo completion",
        ["创建论文 · 自动生成七阶段"] = "Paper created · seven stages prepared",
        ["复制论文资料 · 七阶段清零"] = "Paper copied · stages cleared",
        ["调整论文优先顺序"] = "Manual order changed",
        ["归档论文"] = "Paper archived",
        ["恢复论文"] = "Paper restored",
        ["更新论文资料"] = "Paper details updated",
        ["返修设为不适用 · 从进度分母排除"] = "Revision marked not applicable · taken out of the total",
        ["返修恢复为适用阶段"] = "Revision restored",
        ["添加示例论文 · 可编辑或归档"] = "Sample papers added · editable or archivable",
        ["归档"] = "Archive",
        ["恢复"] = "Restore",
        // ---------- 挂件主体 ----------
        ["拖动标题栏或空白处移动小部件"] = "Drag the title bar or empty space to move the widget",
        ["新增论文"] = "New paper",
        ["新增论文 · Ctrl+N"] = "New paper · Ctrl+N",
        ["论文选项"] = "Paper options",
        ["设置"] = "Settings",
        ["收起到系统托盘，双击托盘图标恢复"] = "Hides to the tray; double-click the tray icon to bring it back",
        ["搜索论文、学科、期刊"] = "Search title, subject, journal",
        ["搜索论文、学科、期刊、合作者或备注"] = "Search title, subject, journal, collaborator or notes",
        ["进行中"] = "Active",
        ["全部论文"] = "All papers",
        ["已归档"] = "Archived",
        ["已收录"] = "Accepted",
        ["‹ 上一页"] = "‹ Previous",
        ["下一页 ›"] = "Next ›",
        ["PaperFlow · 双击打开"] = "PaperFlow · double-click to open",
        ["显示 PaperFlow"] = "Show PaperFlow",
        ["始终置顶 / 取消置顶"] = "Always on top / normal",
        ["放好桌面和开始菜单快捷方式"] = "Create desktop and Start menu shortcuts",
        ["退出"] = "Exit",
        ["资料文件夹："] = "Data folder: ",
        ["\n跨设备到达时间由你的网盘客户端决定，文件夹更新不等于云端上传已完成。"] = "\nArrival on the other PC depends on your sync client; a folder update is not a finished upload.",
        ["同步需要留意 · "] = "Sync needs attention · ",
        ["演示数据 · 所有论文均为虚构 · "] = "Demo data · every paper is fictional · ",
        ["仅供演示导出。"] = "for demonstration exports only.",
        ["已保存"] = "Saved",
        ["修改已记录，快照备份待重试 · "] = "Change recorded, backup snapshot will retry · ",
        ["{0} · {1:HH:mm} · 本地自动备份"] = "{0} · {1:HH:mm} · local backup",
        ["已保存 · "] = "Saved · ",
        ["保存失败 · 本次修改未生效"] = "Save failed · this change was not applied",
        ["保存失败"] = "Save failed",
        ["无法保存，本次修改没有写入。\n\n"] = "Could not save; this change was not written.\n\n",
        ["已新增论文"] = "Paper added",
        ["已置顶"] = "Pinned",
        ["置顶"] = "Pin",
        ["F12 切换置顶"] = "F12 toggles pinning",
        ["紧凑"] = "Compact",
        ["展开"] = "Full",
        ["   ·   已筛选"] = "   ·   filtered",
        ["{0} 篇论文   ·   {1} 篇推进中   ·   {2} 篇已收录"] = "{0} papers   ·   {1} in progress   ·   {2} accepted",
        ["收起隐藏 {0} 篇"] = "Hide {0} hidden",
        ["显示隐藏 {0} 篇"] = "Show {0} hidden",
        ["把这些按设置隐藏的论文收回去"] = "Put the papers hidden by your settings away again",
        ["临时看一眼按当前设置被隐藏的论文，它们会显示成灰底，方便区分"] = "Peek at the papers your settings hide; they appear dimmed so you can tell them apart",
        ["显示或隐藏按阶段隐藏的论文"] = "Peek at, or put away, the papers hidden by stage",
        ["{0} 篇论文 · 当前显示 {1} 篇"] = "{0} papers · showing {1}",
        [" · 按阶段隐藏 {0} 篇"] = " · {0} hidden by stage",
        [" · 阶段分组"] = " · grouped by stage",
        [" · 排序："] = " · sorted by ",
        ["隐藏和翻页仅改变显示，不删除论文。点击论文选项调整。"] = "Hiding and paging only change what you see; nothing is deleted. Open Paper options to adjust.",
        ["所选阶段："] = "Selected stage: ",
        ["从第一篇论文开始"] = "Start with your first paper",
        ["这里暂时没有论文"] = "No papers here right now",
        ["点击右上角 ＋，输入论文标题。\n七个阶段和进度条会自动准备好。"] = "Click ＋ in the top right and type a title.\nThe seven stages and the progress bar arrive automatically.",
        ["论文可能在其他页，或被当前筛选隐藏。\n点击论文选项调整显示范围。"] = "Your papers may be on another page, or hidden by the current filter.\nOpen Paper options to change what is shown.",
        ["查看三篇示例"] = "Add three samples",
        ["调整论文选项"] = "Open Paper options",
        ["收起这条提示"] = "Dismiss this note",
        ["\n拖动调整优先顺序"] = "\nDrag to reorder",
        ["已隐藏 · "] = "Hidden · ",
        ["按其当前阶段，这类论文在你的设置里是隐藏的；点右上角可以收回去"] = "Your settings hide papers at this stage; use the top-right button to put them away again",
        ["{0} 进度 {1}%"] = "{0} · {1}% done",
        ["下一步："] = "Next: ",
        ["（免）"] = "(n/a)",
        ["点击切换；进度按适用阶段等权计算"] = "Click to toggle; progress counts the applicable stages equally",
        ["返修已设为不适用，可在论文资料中恢复"] = "Revision is marked not applicable; restore it in the paper details",
        ["勾选表示进入在审；继续勾选返修或收录后，移出在审分组。"] = "Checking this marks the paper as under review; check Revision or Accepted to leave that group.",
        ["已开始 {0} 天"] = "Started {0} days ago",
        ["开始日期：{0:yyyy-MM-dd}\n已开始 {1} 天"] = "Started {0:yyyy-MM-dd}\n{1} days in",
        ["下一步 "] = "Next ",
        ["\n编辑资料、修改记录、排序、复制、归档"] = "\nEdit details, change history, order, copy, archive",
        ["尚未填写学科、期刊等资料"] = "No subject, journal or other details yet",
        ["{0} 的论文设置"] = "{0} · paper settings",
        ["{0}优先级 · 三个点分别代表高、中、低\n点击修改，按住拖动调整顺序"] = "{0} priority · three dots mean high, medium and low\nClick to change, drag to reorder",
        [" 的优先级："] = " priority: ",
        ["已保存优先顺序"] = "Order saved",
        ["编辑论文资料"] = "Edit paper details",
        ["查看修改记录"] = "View change history",
        ["上移一位"] = "Move up",
        ["下移一位"] = "Move down",
        ["复制为新论文（阶段清零）"] = "Copy as a new paper (stages cleared)",
        ["（副本）"] = " (copy)",
        ["已复制为新论文 · 它已经放在列表最上面"] = "Copied into a new paper · it sits at the top of the list",
        ["归档（保留资料）"] = "Archive (keeps the record)",
        ["恢复到论文列表"] = "Restore to the list",
        ["已归档 · 在论文选项的显示范围里选“已归档”可以再找到它"] = "Archived · choose “Archived” under Paper options → Show to find it again",
        ["已恢复到论文列表"] = "Restored to the list",
        ["优先级"] = "Priority",
        ["修改记录 · "] = "Change history · ",
        ["桌面和开始菜单各放好一个入口。要固定在任务栏，右键那个快捷方式选“固定到任务栏”。"] = "Shortcuts are in place on the desktop and in the Start menu. To pin one, right-click it and choose “Pin to taskbar”.",
        ["快捷方式未能创建。\n"] = "The shortcut could not be created.\n",
        // ---------- 论文选项 ----------
        ["搜索与视图"] = "Search and view",
        ["搜索论文、期刊、学科或合作者"] = "Search by title, journal, subject or collaborator",
        ["显示范围"] = "Show",
        ["排序方式"] = "Sort",
        ["紧凑视图（保留七阶段）"] = "Compact view (keeps all seven stages)",
        ["只显示这些优先级"] = "Only show these priorities",
        ["暂时隐藏的阶段"] = "Stages to hide for now",
        ["隐藏所选阶段的论文"] = "Hide papers at the selected stages",
        ["按最后一个已勾选阶段归类；未勾选时归入开题。\n例如：在审后进入返修，会重新显示。"] = "A paper is grouped by its last checked stage; with nothing checked it counts as Proposal.\nMoving on from Under review to Revision brings it back.",
        ["挂件右上角有个“显示隐藏 N 篇”的临时开关：点一下就能看一眼这些论文，展开时它们显示成灰底并带“已隐藏”标记，这里的设置不受影响。"] = "The widget's top right has a “Show N hidden” switch: it peeks at these papers once, dimmed and tagged “Hidden”, without changing anything here.",
        ["翻页方式"] = "Paging",
        ["优先级：高 → 中 → 低。\n阶段分组：第一页排除所选阶段，第二页只看所选阶段。\n阶段分页会将隐藏项放到第二页；优先级筛选仍生效。"] = "Priority: high → medium → low.\nStage groups: page one leaves the selected stages out, page two shows only them.\nStage paging puts hidden papers on page two; the priority filter still applies.",
        ["显示全部"] = "Show everything",
        ["{0}优先级"] = "{0} priority",
        ["当前推进"] = "In progress",
        ["所选阶段"] = "Selected stage",
        ["论文列表"] = "Paper list",
        ["已进入{0} · 它被放到了第 {1} 页"] = "Now in {0} · moved to page {1}",
        ["翻到第 {0} 页"] = "Go to page {0}",
        ["已进入{0} · 按当前设置，这类论文被隐藏了"] = "Now in {0} · your settings hide these papers",
        ["立即显示"] = "Show now",
        // ---------- 备份与导入 ----------
        ["导出完整备份"] = "Export a full backup",
        ["论文进度-{0:yyyyMMdd-HHmm}.json"] = "paperflow-{0:yyyyMMdd-HHmm}.json",
        ["论文进度备份 (*.json)|*.json"] = "PaperFlow backup (*.json)|*.json",
        ["请另选位置，不要覆盖正在使用的资料文件。"] = "Choose another place; do not overwrite the file the app is using.",
        ["完整备份已导出"] = "Full backup exported",
        ["导出失败"] = "Export failed",
        ["导入备份（只添加新编号，不覆盖已有论文）"] = "Import a backup (adds new ids, never overwrites)",
        ["文件超过 30 MB。"] = "The file is larger than 30 MB.",
        ["导入了 {0} 篇新论文"] = "Imported {0} new papers",
        ["导入完成"] = "Import finished",
        ["新增 {0} 篇，已有编号的记录保持原样。\n导入前资料已自动备份。"] = "Added {0} papers; records that already exist are untouched.\nYour data was backed up first.",
        ["导入失败"] = "Import failed",
        ["文件没有导入，原资料保持原样。\n"] = "Nothing was imported; your data is unchanged.\n",
        // ---------- 演示数据 ----------
        ["管理学"] = "Management",
        ["经济学"] = "Economics",
        ["公共管理"] = "Public administration",
        ["示例 · 论文 A"] = "Sample · Paper A",
        ["示例 · 论文 B"] = "Sample · Paper B",
        ["示例 · 论文 C"] = "Sample · Paper C",
        ["完成投稿前检查"] = "Finish the pre-submission checks",
        ["整理审稿意见与回复"] = "Draft the response to reviewers",
        ["整理语料与数据"] = "Organize the corpus and data",
        ["已加入三篇示例，可编辑或归档"] = "Three samples added; edit or archive them freely",
        ["中文"] = "Chinese",
        ["英文"] = "English",
        // ---------- 论文资料对话框 ----------
        ["论文资料"] = "Paper details",
        ["让下一步更清楚"] = "Make the next step obvious",
        ["七阶段在小部件上直接勾选；这里保存论文的完整资料。"] = "The seven stages are checked on the widget itself; this is where the full record lives.",
        ["论文标题"] = "Paper title",
        ["学科"] = "Subject",
        ["语言"] = "Language",
        ["合作者"] = "Collaborators",
        ["目标期刊"] = "Target journal",
        ["当前投稿状态"] = "Submission status",
        ["下一步行动"] = "Next action",
        ["开始日期"] = "Start date",
        ["下一步截止日期（可留空）"] = "Next deadline (optional)",
        ["返修不适用（无需返修即录用，按其余六阶段计算）"] = "Revision not applicable (accepted without one; counts the other six stages)",
        ["结局"] = "Outcome",
        ["备注 / 投稿与返修历史"] = "Notes / submission and revision history",
        ["已开始 {0} 天   ·   上次编辑 {1:yyyy-MM-dd HH:mm}"] = "Started {0} days ago   ·   last edited {1:yyyy-MM-dd HH:mm}",
        ["进度表示适用阶段的完成比例。勾选“收录”后，小部件显示已录用；若你用“收录”表示数据库收录，可在结局中另记录用时间。"] = "Progress is the share of applicable stages completed. Checking “Accepted” makes the widget show the paper as accepted; if you use that stage for database indexing instead, note the acceptance date under Outcome.",
        ["请填写论文标题。"] = "Please enter a paper title.",
        ["请填写有效日期，截止日期也可以留空。"] = "Please enter a valid date; the deadline may be left empty.",
        ["日期需在 1900—2200 年之间。"] = "Dates must fall between 1900 and 2200.",
        ["保存资料"] = "Save details",
        // ---------- 新增论文 ----------
        ["新增"] = "Add",
        ["写下论文标题"] = "Type the paper title",
        ["自动附带七个阶段，资料可以稍后补充。"] = "Seven stages come with it; details can wait.",
        ["取消"] = "Cancel",
        // ---------- 设置：分类 ----------
        ["外观"] = "Appearance",
        ["字体与文字"] = "Type & text",
        ["视图与分页"] = "View & paging",
        ["同步与启动"] = "Sync & startup",
        ["关于与反馈"] = "About & feedback",
        ["让外观像你自己的桌面"] = "Make it look like your desktop",
        ["所有改动都会立刻作用在挂件上；点取消会恢复打开设置前的样子。实心预览是你正在用的那套。"] = "Each change applies to the widget straight away; Cancel restores what you had. The highlighted row is the one in use.",
        ["布局"] = "Layout",
        ["主题（按风格分组，共 {0} 套）"] = "Themes (grouped by family, {0} in all)",
        ["跟随 Windows 的浅色/深色设置"] = "Follow the Windows light/dark setting",
        ["进度条厚度"] = "Progress bar thickness",
        ["细 · 6"] = "Thin · 6",
        ["中 · 14"] = "Medium · 14",
        ["粗 · 20"] = "Thick · 20",
        ["特粗 · 28"] = "Extra thick · 28",
        ["主色…"] = "Accent…",
        ["底色…"] = "Background…",
        ["恢复主题色"] = "Reset to the theme colour",
        ["背景不透明度"] = "Background opacity",
        ["背景不透明度 · {0:0}%（文字保持清晰）"] = "Background opacity · {0:0}% (text stays crisp)",
        ["背景图片"] = "Background image",
        ["当前没有背景图片，用的是主题底色。"] = "No background image; the theme's own colour is used.",
        ["正在使用："] = "In use: ",
        ["找不到文件："] = "File not found: ",
        ["\n文字要看清，把上面的不透明度和下面的遮罩一起调到合适为止。"] = "\nTo keep the text readable, balance the opacity above with the scrim below.",
        ["\n换一张，或者点清除。"] = "\nChoose another one, or click Clear.",
        ["选择背景图片"] = "Choose a background image",
        ["图片 (*.png;*.jpg;*.jpeg;*.webp;*.bmp;*.gif)|*.png;*.jpg;*.jpeg;*.webp;*.bmp;*.gif|所有文件 (*.*)|*.*"] = "Images (*.png;*.jpg;*.jpeg;*.webp;*.bmp;*.gif)|*.png;*.jpg;*.jpeg;*.webp;*.bmp;*.gif|All files (*.*)|*.*",
        ["选择图片…"] = "Choose image…",
        ["清除"] = "Clear",
        ["打开所在文件夹"] = "Open folder",
        ["图片遮罩"] = "Image scrim",
        ["图片遮罩 · {0:0}%（越大文字越清楚，越小越看得见图片）"] = "Image scrim · {0:0}% (higher keeps text clearer, lower shows more of the image)",
        ["文字分三档"] = "Three text tiers",
        ["标题、正文、次要各管一层。字体和颜色留空就跟随基础设置或主题。"] = "Title, body and caption each have their own tier. Leave a font or colour empty to follow the base setting or the theme.",
        ["基础字体"] = "Base font",
        ["基础字号"] = "Base size",
        ["界面缩放（文字和间距一起缩放）"] = "Interface zoom (scales text and spacing together)",
        ["调整字号或界面缩放时，自动放大窗口（最多占屏幕工作区的一半）"] = "Grow the window while adjusting size or zoom (up to half of the work area)",
        ["跟随基础字体"] = "Follow the base font",
        ["字号比例"] = "Size ratio",
        ["字号比例 · {0:0}%"] = "Size ratio · {0:0}%",
        ["颜色跟随主题。"] = "Colour follows the theme.",
        ["对比度只有 {0:0.0}:1，压在这个主题的卡片底色上会看不清，建议换深一点或浅一点的颜色。"] = "Contrast is only {0:0.0}:1, hard to read on this theme's card colour; try a darker or lighter shade.",
        ["对比度 {0:0.0}:1，和卡片底色区分得开。"] = "Contrast {0:0.0}:1 — clearly distinct from the card colour.",
        ["文字颜色…"] = "Text colour…",
        ["恢复主题默认"] = "Reset to the theme default",
        ["标题"] = "Title",
        ["论文标题、产品名"] = "Paper titles, product name",
        ["正文"] = "Body",
        ["阶段标签、天数、下一步、按钮、表单"] = "Stage labels, day counts, next step, buttons, forms",
        ["次要"] = "Caption",
        ["汇总行、页脚、提示文字"] = "Summary line, footer, hints",
        ["按当前窗口和字号，大约能完整显示 {0} 篇论文。"] = "At this window and text size, about {0} cards fit whole.",
        ["当前窗口放不下整张卡片，可以把窗口调大或把缩放调小。"] = "A whole card no longer fits; enlarge the window or reduce the zoom.",
        ["字号 · {0:0}（只改文字大小，不动间距）"] = "Text size · {0:0} (text only, spacing untouched)",
        ["界面缩放 · {0:0}%（文字和间距一起缩放）"] = "Interface zoom · {0:0}% (text and spacing together)",
        ["列表怎么显示"] = "List display",
        ["论文标题加粗"] = "Bold paper titles",
        ["操作后在底部显示提示条"] = "Show a note at the bottom after an action",
        ["提示条只在这些时候出现：勾选阶段后论文被隐藏或被挪到别的页、归档、复制。正常的勾选不会弹。"] = "The note only appears when a checked stage hides the paper or moves it to another page, and when you archive or copy. Ordinary checks stay quiet.",
        ["音效"] = "Sound",
        ["音色"] = "Voice",
        ["音量"] = "Volume",
        ["音量 · {0:0}%"] = "Volume · {0:0}%",
        ["试听完成音"] = "Preview completion",
        ["试听取消音"] = "Preview undo",
        ["试听收录音"] = "Preview accepted",
        ["音效默认关闭，只在本机生效、不随同步跑到别的电脑；勾满七个阶段时换成一小段奖励音。"] = "Sound is off by default and stays on this PC — it is not synced. Checking all seven stages plays a short reward chime.",
        ["搜索、筛选、排序、紧凑视图、隐藏哪些阶段、翻页方式和显示范围都在挂件右上角的“论文选项”里，那里改的是此刻看到什么。这里只放长期偏好。"] = "Search, filters, sorting, compact view, hidden stages, paging and what is shown all live under “Paper options” in the widget's top right — that is about what you see right now. This page holds long-term preferences.",
        ["字号、界面缩放和三档字体在“字体与文字”里。"] = "Text size, interface zoom and the three text tiers live under “Type & text”.",
        ["铺满屏幕时界面会不会挤，取决于字号和界面缩放的组合。字号很大时阶段标签会换行、卡片自然变高，一屏能看到的论文会变少，这是正常的。"] = "How crowded the widget feels depends on the mix of text size and zoom. With very large text the stage labels wrap, cards grow taller and fewer papers fit on screen — that is expected.",
        ["界面语言"] = "Interface language",
        ["跟随系统就是看 Windows 的显示语言；保存后挂件会自动重启一次换成新语言，你的资料一个字都不动。"] = "“Follow system” uses the Windows display language; after saving, the widget restarts once into the new language and your data stays exactly as it is.",
        ["优先级设为"] = "Priority set to ",
        // ---------- 设置：同步与启动 ----------
        ["论文同步与备份"] = "Sync and backup",
        ["正在使用同步文件夹\n"] = "Using a sync folder\n",
        ["打开同步资料文件夹"] = "Open the synced data folder",
        ["如果你使用 OneDrive / 百度网盘 / Dropbox / 坚果云 等同步文件夹，在同一个文件夹下，其他电脑收到后会同步你的设置哦。"] = "If you use OneDrive / Baidu Netdisk / Dropbox / Nutstore or any other synced folder, keep the install folder in the same place and your other PCs pick these settings up as soon as the files arrive.",
        ["导出备份"] = "Export backup",
        ["导入备份"] = "Import backup",
        ["本地资料"] = "Local data",
        ["启动"] = "Startup",
        ["登录 Windows 时自动打开"] = "Open automatically when I sign in to Windows",
        ["× 收起到托盘，双击托盘图标恢复。更新时请先从托盘菜单退出，再打开固定启动入口。"] = "× hides the widget in the tray; double-click the tray icon to bring it back. Before updating, exit from the tray menu and then open the fixed launcher.",
        ["快捷方式"] = "Shortcuts",
        ["挂件本身不进任务栏，用这两个入口打开最省事。它们指向固定启动入口，以后换了版本也不用重建。"] = "The widget stays out of the taskbar, so these two entries are the easiest way back in. They point at the fixed launcher, so a new version needs no new shortcut.",
        ["这台电脑上还没找到固定启动入口（说明现在是从程序文件直接打开的），快捷方式会先指向当前这个程序文件。以后用固定启动入口打开一次、再回来重新勾选一次，会更稳妥。"] = "No fixed launcher was found on this PC (the app is running straight from its program file), so the shortcut will point at that file. Open it once through the fixed launcher and tick this again afterwards to be safe.",
        ["桌面上放一个入口"] = "Put one on the desktop",
        ["开始菜单里放一个入口"] = "Put one in the Start menu",
        ["勾上表示放好，取消勾选表示移除，保存设置时生效；不勾也不影响程序运行。任务栏图标不能由程序自己钉：右键上面那个快捷方式，选“固定到任务栏”就留在任务栏上了。"] = "Ticking puts it there, clearing the tick removes it, and it takes effect when you save; leaving both empty changes nothing else. Windows does not let an app pin itself to the taskbar: right-click that shortcut and choose “Pin to taskbar”.",
        ["打开程序文件夹"] = "Open the program folder",
        // ---------- 设置：更新 ----------
        ["更新"] = "Updates",
        ["更新提示"] = "Update prompts",
        ["每次都提示"] = "Every launch",
        ["每天一次"] = "Once a day",
        ["不提示"] = "Never",
        ["现在检查一次"] = "Check now",
        ["正在检查…"] = "Checking…",
        ["上次检查：{0:yyyy-MM-dd HH:mm}"] = "Last checked: {0:yyyy-MM-dd HH:mm}",
        ["还没检查过"] = "Not checked yet",
        ["已经是最新版（{0}）。"] = "You are on the newest version ({0}).",
        ["发现新版本 {0}：切回挂件就能下载。"] = "Version {0} is available: switch back to the widget to download it.",
        ["这次检查没成功：{0}"] = "The check did not go through: {0}",
        ["检查更新没成功：{0}"] = "The update check did not go through: {0}",
        ["现在再试一次"] = "Try again now",
        ["下载卡住了：很久没有收到数据。"] = "The download stalled: no data arrived for a long while.",
        ["下载没完成：{0}可以再试一次；网络慢的时候可能要好几分钟。"] = "The download did not finish: {0}Try again — over a slow connection it can take several minutes.",
        ["连不上 GitHub，可能是网络或代理的问题。"] = "GitHub could not be reached — usually a network or proxy problem.",
        ["连接 GitHub 超时，可能是网络慢或被拦住了。"] = "Connecting to GitHub timed out; the network may be slow or blocked.",
        ["GitHub 上的更新清单读不出来。"] = "The update manifest on GitHub could not be read.",
        ["上次检查没成功（{0:yyyy-MM-dd HH:mm}）：{1}"] = "Last check did not go through ({0:yyyy-MM-dd HH:mm}): {1}",
        ["这次没连上 GitHub（{0}）"] = "GitHub could not be reached this time ({0})",
        ["这次没连上 GitHub，没能检查更新。{0}可以稍后再试，也可以把更新提示设为“不提示”。"] = "GitHub could not be reached, so updates were not checked. {0}Try again later, or set update prompts to “Never”.",
        ["检查更新失败：{0}"] = "Update check failed: {0}",
        ["更新清单的版本号无效。"] = "The update manifest has an invalid version.",
        ["更新清单的校验值无效。"] = "The update manifest has an invalid checksum.",
        ["更新清单的文件大小无效。"] = "The update manifest has an invalid file size.",
        ["更新清单的下载地址无效。"] = "The update manifest has an invalid download address.",
        ["更新清单的下载地址不是程序文件。"] = "The update manifest does not point at a program file.",
        ["有新版本 {0}"] = "Version {0} is available",
        ["下载并安装"] = "Download and install",
        ["正在下载 {0}%"] = "Downloading {0}%",
        ["下载失败"] = "Download failed",
        ["更新包校验失败，已丢弃，没有改动现在的程序。"] = "The download failed its checksum, so it was discarded and nothing was changed.",
        ["新版本已就绪 {0}，重启后生效。"] = "Version {0} is ready; it starts after a restart.",
        ["重启并更新"] = "Restart now",
        ["稍后"] = "Later",
        ["正在下载更新 {0}%"] = "Downloading the update {0}%",
        ["先不更新，下次启动再说"] = "Not now, ask again next launch",
        ["正在下载…"] = "Downloading…",
        ["重试"] = "Try again",
        ["没能自动重启，请自己从托盘退出再打开：{0}"] = "Could not restart automatically; exit from the tray and open it again: {0}",
        ["找不到要重新打开的程序文件。"] = "There is no program file to open again.",
        ["更新在后台下载，不影响你继续用。"] = "The update downloads in the background; keep working as usual.",
        ["重启后请从托盘重新打开；正在编辑的窗口会先关闭。"] = "After restarting, open the widget from the tray again; any open window will close first.",
        ["这个版本太旧或清单不完整，没有安装。"] = "That version is too old or its manifest is incomplete, so nothing was installed.",
        ["从 GitHub 下载新版本"] = "Download the new version from GitHub",
        ["检查更新只读 GitHub 上的一份清单，只下载、不上传，论文数据不会被发送出去。选“不提示”就一次网络请求都不发，那时也可以随时按这个按钮手动检查。"] = "Checking for updates reads one small manifest on GitHub: it downloads and never uploads, and your papers are never sent anywhere. With “Never” selected the app makes no request at all, and you can still use this button whenever you like.",
        ["请指定音效输出目录。"] = "Please give the sound output folder.",
        ["请指定主题一览图的输出目录。"] = "Please give the theme gallery output folder.",
        ["请指定宣传图输出目录。"] = "Please give the promotional image output folder.",
        // ---------- 关于与反馈 ----------
        ["版本 {0}"] = "Version {0}",
        ["MIT 许可 · Copyright (c) 2026 Panwang Yuang\n不需要注册账号，论文数据只存在你自己的电脑上。程序只在检查更新时访问 GitHub，只下载、不上传。"] = "MIT licence · Copyright (c) 2026 Panwang Yuang\nNo account needed, and your papers stay on your own PC. The app only reaches GitHub when checking for updates, and only to download — never to upload.",
        ["打开主页"] = "Home page",
        ["开 GitHub issue"] = "Open a GitHub issue",
        ["写邮件反馈"] = "Send feedback by e-mail",
        ["复制邮箱"] = "Copy e-mail address",
        ["遇到问题发邮件到 pwya1998@126.com，或在 GitHub 上开 issue（截图和文字都可以），两条路我都会看。"] = "Mail pwya1998@126.com or open a GitHub issue — screenshots welcome. I read both.",
        ["保存设置"] = "Save settings",
        ["设置未能保存。\n"] = "The settings could not be saved.\n",
        // ---------- 系统层：快捷方式、开机启动、存档、迁移 ----------
        ["PaperFlow · 论文投稿进度"] = "PaperFlow · paper submission tracker",
        ["桌面"] = "Desktop",
        ["开始菜单"] = "Start menu",
        ["找不到可以指向的程序文件。"] = "There is no program file to point at.",
        ["快捷方式保存位置无效。"] = "The shortcut location is not valid.",
        ["这台电脑缺少 Windows 脚本组件，无法创建快捷方式。"] = "This PC is missing the Windows scripting component, so the shortcut cannot be created.",
        ["这台电脑缺少 Windows 脚本组件，无法读取快捷方式。"] = "This PC is missing the Windows scripting component, so the shortcut cannot be read.",
        [" 不是本程序创建的快捷方式，没有删除。请自己确认后手动删除它。"] = " is not a shortcut this app created, so it was left alone. Please check it and delete it yourself if you want.",
        ["{0}：{1}"] = "{0}: {1}",
        ["启动入口不可用，请从固定的启动器打开后再设置。"] = "The launcher is unavailable; open the app from the fixed launcher first and then change this setting.",
        ["无法打开论文资料，程序没有覆盖原数据。\n\n"] = "The paper data could not be opened, and nothing was overwritten.\n\n",
        ["已恢复备份"] = "Backup restored",
        ["PaperFlow 已升级"] = "PaperFlow was upgraded",
        ["\n\n原目录 %LOCALAPPDATA%\\PaperProgress 未被修改，确认新版本正常后可以自行删除。"] = "\n\nThe old %LOCALAPPDATA%\\PaperProgress folder was left untouched; you may delete it once the new version looks right.",
        ["已把原 PaperProgress 的本机资料迁移到新目录，原目录保持不动。"] = "Local data was copied from the old PaperProgress folder; the original folder was left alone.",
        ["资料无法读取。原文件已保留在 {0}，请从备份恢复。"] = "The data could not be read. The damaged file is kept at {0}; please restore from a backup.",
        ["已从上次备份恢复。损坏原文件保留在：{0}"] = "Recovered from the last backup. The damaged file is kept at: {0}",
        ["资料为空。"] = "The data file is empty.",
        ["文件版本或结构不受支持。"] = "That file version or structure is not supported.",
        ["论文数量超过 10000 篇。"] = "More than 10000 papers.",
        ["论文记录不能为 null。"] = "A paper record cannot be null.",
        ["论文编号重复。"] = "Duplicate paper ids.",
        ["论文编号或标题无效（标题最多 500 字）。"] = "A paper id or title is invalid (titles are limited to 500 characters).",
        ["必须包含完整的七个标准阶段，且完成与不适用不能同时选中。"] = "All seven standard stages are required, and done cannot be combined with not applicable.",
        ["仅返修阶段允许设为不适用。"] = "Only the revision stage may be marked not applicable.",
        ["修改记录无效。"] = "A change history entry is invalid.",
        ["优先级必须是高、中或低。"] = "Priority must be high, medium or low.",
        ["每日备份失败："] = "Daily backup failed: ",
        ["本机自动保存"] = "Saved on this PC",
        ["本机已保存"] = "Saved on this PC",
        ["本机已保存 · 等待写入同步文件夹"] = "Saved on this PC · waiting for the sync folder",
        ["本机已保存 · {0} 个同步文件暂无法读取，将重试"] = "Saved on this PC · {0} sync files cannot be read yet; will retry",
        ["本机已保存 · 同步待重试（{0}）"] = "Saved on this PC · sync will retry ({0})",
        ["同步文件夹已更新 · "] = "Sync folder updated · ",
        ["同步文件夹已更新 · {0} 条记录含更新版本的字段，已保留待升级后生效"] = "Sync folder updated · {0} records hold fields from a newer version and wait for an upgrade",
        ["本机同步标识损坏，请保留资料后重新配置。"] = "The local sync id is damaged; keep your data and configure it again.",
        ["同步记录过大。"] = "The sync record is too large.",
        ["同步记录为空。"] = "The sync record is empty.",
        ["同步记录版本不受支持："] = "Unsupported sync record version: ",
        ["本机生成的同步记录含未知字段。"] = "A sync record written by this PC holds unknown fields.",
        ["同步记录格式不受支持。"] = "Unsupported sync record format.",
        ["空修改记录。"] = "Empty change record.",
        ["同步字段缺失。"] = "A sync field is missing.",
        ["论文编号无效。"] = "Invalid paper id.",
        ["文字字段不能为空值。"] = "A text field cannot be null.",
        ["论文标题无效。"] = "Invalid paper title.",
        ["优先级无效。"] = "Invalid priority.",
        ["日期无效。"] = "Invalid date.",
        ["阶段无效。"] = "Invalid stage.",
        ["排序无效。"] = "Invalid order.",
        ["历史记录无效。"] = "Invalid history entry.",
        ["同步文件过大："] = "Sync file too large: ",
    };
}
