<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>PaperFlow</AssemblyName>
    <RootNamespace>PaperFlow</RootNamespace>
    <Version>1.13.4</Version>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Product>PaperFlow</Product>
    <Description>PaperFlow 离线论文投稿进度桌面小部件</Description>
  </PropertyGroup>
  <ItemGroup><Resource Include="Assets\app.ico"/></ItemGroup>
</Project>
